#!/usr/bin/env bash

. $(dirname $(readlink -f "$0"))/buildvm-base.sh

export IMAGE=${IMAGE:-"Ubuntu 16.04 LTS (Xenial) 64 Bit"}
export CLOUD_CONFIG=${CLOUD_CONFIG:-"cloud-config-xenial.txt"}

buildvm
